### ISSUE TITLE
[FeatureRequest] Allow multiple single-line comments in languages that don't support multiline comments.

### ISSUE THREAD

**Issue by BraynStorm** [Gismo359/todo-highlight#1]
Currently, only the first line is colorized.

My proposal is to allow fusion of multiple single-line comments into a single "comment". Python is a pseudo example of language without multiline comments. There are string literals that are multiline but... come on.

Example of what happens now:
![image](https://user-images.githubusercontent.com/1812982/149134930-37c3db7d-8acf-40be-9a4b-b7dc820af31e.png)

In this image, all 3 lines of the 'comment' should be yellow when the feature is implemented.

**Comment by Gismo359** [comment]
Implemented in `0.1.0`
